{
 "title": "Unifi Protect - Sensors",
 "description": "exporter-unifi-protect Dashboard - https://github.com/hoomy-official/exporter-unifi-protect",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(sensor_info,job)" } },
   {
    "name": "instance",
    "label": "Instances",
    "query": {
     "query": "label_values(sensor_info{job=\"$job\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sensor_temperature_celsius{job=\"$job\", name=~\"$instance\"} * 1.8 )+ 32",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(sensor_temperature_celsius{job=\"$job\", name=~\"$instance\"} * 1.8 )+ 32",
     "legendFormat": "Temperature - {{name}}"
    }
   ]
  },
  {
   "title": "Sensor Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_humidity_percentage{job=\"$job\", name=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sensor_humidity_percentage", "legendFormat": "Humidity - {{name}}" }
   ]
  },
  {
   "title": "Sensor Light ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_light_lux{job=\"$job\", name=~\"$instance\"}",
     "legendFormat": "Lux - {{name}}"
    }
   ]
  },
  {
   "title": "Sensor Light ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sensor_light_lux{job=\"$job\", name=~\"$instance\"}",
     "legendFormat": "Lux - {{name}}"
    }
   ]
  },
  {
   "title": "Sensor Motion",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "sensor_is_motion_detected", "legendFormat": "Motion - {{detected_period}}" }
   ]
  },
  {
   "title": "Extra Features - Door/Window Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor Opened",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "targets": [
      { "expr": "sensor_is_opened", "legendFormat": "Opened- {{detected_period}}" }
     ]
    }
   ]
  },
  {
   "title": "Sensor Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor Battery",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sensor_battery_status_percentage{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Battery"
      }
     ]
    },
    {
     "title": "Sensor Bluetooth Signal Quality",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sensor_bluetooth_signal_quality{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Signal Quality"
      }
     ]
    },
    {
     "title": "Sensor Bluetooth  Signal Stength",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "RSSI" } },
     "targets": [
      {
       "expr": "sensor_bluetooth_signal_strength{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Signal Stength"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor Status - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor Battery",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_battery_status_percentage{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Battery"
      }
     ]
    },
    {
     "title": "Sensor Bluetooth Signal Quality",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_bluetooth_signal_quality{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Signal Quality"
      }
     ]
    },
    {
     "title": "Sensor Bluetooth  Signal Stength",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "RSSI" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_bluetooth_signal_strength{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}} - Signal Stength"
      }
     ]
    },
    {
     "title": "Sensor Up Since ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_up_since_gauge{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sensor Connected Since ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_connected_since_gauge{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sensor Last Seen",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_last_seen_gauge{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Firmware Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_info{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{firmwareVersion}} "
      }
     ]
    },
    {
     "title": "Hardware Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_info{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "{{hardwareRevision}}"
      }
     ]
    },
    {
     "title": "Sensor Status",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sensor_is_provisioned{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sensor_is_adopted{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Adopted"
      },
      {
       "expr": "sensor_is_adopted_by_other{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Adopted by Other"
      },
      {
       "expr": "sensor_is_adopting{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Adopting"
      },
      {
       "expr": "sensor_is_attempting_to_connect{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Attempting to Connect"
      },
      {
       "expr": "sensor_is_connected{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Connected"
      },
      {
       "expr": "sensor_is_downloading_f_w{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Downloading Firmware"
      },
      {
       "expr": "sensor_is_rebooting{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Rebooting"
      },
      {
       "expr": "sensor_is_restoring{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Restoring"
      },
      {
       "expr": "sensor_is_ssh_enabled{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "SSH Enabled"
      },
      {
       "expr": "sensor_is_updating{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Updating"
      },
      {
       "expr": "sensor_can_adopt{job=\"$job\", name=~\"$instance\"}",
       "legendFormat": "Can Adopt"
      }
     ]
    }
   ]
  }
 ]
}