{{- if and (.Values.metrics.enabled) (.Values.metrics.podMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "exporter-unifi-protect.fullname" . }}
  namespace: {{ .Values.metrics.podMonitor.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "exporter-unifi-protect.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: http-metrics
      {{- if .Values.metrics.podMonitor.honorLabels }}
      honorLabels: {{ .Values.metrics.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.interval }}
      interval: {{ .Values.metrics.podMonitor.interval | quote }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      path: {{ .Values.metrics.podMonitor.path | quote }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout | quote }}
      {{- end }}
  {{- if .Values.metrics.podMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.podMonitor.jobLabel | quote }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "exporter-unifi-protect.selectorLabels" . | nindent 6 }}
      {{- with .Values.metrics.podMonitor.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
